sudo: false
language: node_js
node_js:
    - '5'
    - '6'
env:
    - TSI2_LING7='build'
    - TSI2_LING7='test'
branches:
    only:
        - master
script:
    - echo npm run $TSI2_LING7
    - npm run $TSI2_LING7
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    fqdn: itaigi.tw
    name: iTaiGi Auto Deploy Bot
    on:
        branch: master

